name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test-native:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and run tests
        run: cargo test --lib --verbose
  
  wasm-build:
    needs: build-and-test-native
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install wasm-pack
        run: cargo install --git https://github.com/rustwasm/wasm-pack.git
      - name: Build package
        run: wasm-pack build --scope maru0137
      - name: Upload package
        uses: actions/upload-artifact@v1
        with:
          name: pkg
          path: pkg
